### ISSUE TITLE
The instantiated example (e.g., SimpleStringMatcher extend by MatcherURL, MatcherYAAAJena or MatcherYAAAOwlApi)) is very very important!!

### ISSUE THREAD

**Issue by liweizhuo001** [dwslab/melt#100] opened 2021-08-22 09:10 UTC
website: https://dwslab.github.io/melt/matcher-packaging/seals 
Package Your First Matcher
Prerequisites: Maven and Java must be installed.

**### You can use the examples/simpleSealsMatcher as a template and change it according to your needs. However, if you take a close look, you can see that it is sufficient to use the pom.xml as template since the packaging is managed through maven.**

**###You specify the matcher class in the <oaei.mainClass> tag. The matcher must implement interface IMatcher <ModelClass, AlignmentClass, ParameterClass>. Note that the easiest way to develop your system is to extend any of the convenience matcher classes such as MatcherURL, MatcherYAAAJena or MatcherYAAAOwlApi rather than implementing the interface yourself.**

We need a real exmaple added in this project. If we directly package this project by "mvn clean package"
**The generated package can not pass the evulation in the case 2 in this example.**
https://dwslab.github.io/melt/matcher-evaluation#more-complex-evaluation-example 
The error information is **"The result of seals matcher is an empty file."** and **the resulting alignment file named systemAlignment.rdf. can not be generated.**

**How to develop one system (e.g., LevenshteinMatcher or SimpleStringMatcher) is to extend any of the convenience matcher classes such as MatcherURL, MatcherYAAAJena or MatcherYAAAOwlApi** is our concern problem.

**One instantiated exampe (LevenshteinMatcher or SimpleStringMatcher extend by MatcherURL, MatcherYAAAJena or MatcherYAAAOwlApi) is important for us to deeply understand this maven project. Lacking it will spend us lots of time to explore the package our Matcher, which is not convenience for us to participate OAEI Campaign.**

**Comment by liweizhuo001** [comment] 2021-08-22 09:17
https://github.com/dwslab/melt/tree/master/examples/simpleSealsMatcher needs to add an instantiated exampe (LevenshteinMatcher or SimpleStringMatcher extend by MatcherURL, MatcherYAAAJena or MatcherYAAAOwlApi).

**Comment by sven-h** [comment] 2021-08-22 11:52
Hi,

the example project should work out of the box and also return a meaningful result.
As defined in the [pom file](https://github.com/dwslab/melt/blob/master/examples/simpleSealsMatcher/pom.xml#L15), it uses the [SimpleStringMatcher](https://github.com/dwslab/melt/blob/master/examples/simpleSealsMatcher/src/main/java/de/uni_mannheim/informatik/dws/melt/demomatcher/SimpleStringMatcher.java) contained in the project.

This matcher uses a `OntModel ` (Jena) but MELT also has interfaces for OWLAPI and it is possible to extend it to other semantic web libraries or your own representation of the ontology.

Can you provide the log file of your run (packaging/evaluation) so that we can check where the actualy error is.

Best regards
Sven

**Comment by liweizhuo001** [comment] 2021-08-22 14:17
2021-08-22 22:16:55 INFO  [main                          ] 194  in MatcherSeals         - Unzip seals matcher simpleSealsMatcher-1.0-seals_external.zip now.
2021-08-22 22:16:55 INFO  [main                          ] 125  in Track                - Track cache folder is: /Users/liweizhuo/oaei_track_cache
2021-08-22 22:16:55 INFO  [main                          ] 48   in ExecutionRunner      - Running matcher SEALS Matcher on testcase mouse-human-suite (track anatomy_track).
2021-08-22 22:16:55 INFO  [main                          ] 142  in ExternalProcess      - Execute now following external process (command, directory, custom environment variables):
2021-08-22 22:16:55 INFO  [main                          ] 143  in ExternalProcess      - command        : java -jar /var/folders/9c/_pvrhxjs2c110syrwl6vy0b00000gn/T/seals-omt-client-v7.0.5.jar /var/folders/9c/_pvrhxjs2c110syrwl6vy0b00000gn/T/meltUnzip-2146192345999266667 -o file:/Users/liweizhuo/oaei_track_cache/oaei.webdatacommons.org/anatomy_track/anatomy_track-default/mouse-human-suite/source.rdf file:/Users/liweizhuo/oaei_track_cache/oaei.webdatacommons.org/anatomy_track/anatomy_track-default/mouse-human-suite/target.rdf -f /var/folders/9c/_pvrhxjs2c110syrwl6vy0b00000gn/T/alignment7443963295898901548.rdf -z
2021-08-22 22:16:55 INFO  [main                          ] 145  in ExternalProcess      - directory      : /private/var/folders/9c/_pvrhxjs2c110syrwl6vy0b00000gn/T/meltSealsHome-2959239414730551835
2021-08-22 22:16:55 INFO  [main                          ] 146  in ExternalProcess      - environmentVars: {SEALS_HOME=/private/var/folders/9c/_pvrhxjs2c110syrwl6vy0b00000gn/T/meltSealsHome-2959239414730551835}
2021-08-22 22:16:56 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): Exception in thread "main" java.lang.NoClassDefFoundError: eu/sealsproject/platform/res/tool/bundle/factory/PackageCreationException
2021-08-22 22:16:56 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): 	at java.base/java.lang.Class.forName0(Native Method)
2021-08-22 22:16:56 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): 	at java.base/java.lang.Class.forName(Class.java:427)
2021-08-22 22:16:56 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): 	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
2021-08-22 22:16:56 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): Caused by: java.lang.ClassNotFoundException: eu.sealsproject.platform.res.tool.bundle.factory.PackageCreationException
2021-08-22 22:16:56 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
2021-08-22 22:16:56 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
2021-08-22 22:16:56 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
2021-08-22 22:16:56 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): 	... 3 more
2021-08-22 22:16:56 ERROR [main                          ] 261  in MatcherSeals         - The result of seals matcher is an empty file. This typically happens when the matcher throws an error (see log messages of ExternalSEALS).In some cases this happens because the matcher does not expect an input alignment. You can solve this by setting  doNotUseInputAlignment to true in MatcherSeals.
2021-08-22 22:16:56 ERROR [main                          ] 54   in MatcherURL           - Tool Exception!
de.uni_mannheim.informatik.dws.melt.matching_base.MatchingException: The result of seals matcher is an empty file.
	at de.uni_mannheim.informatik.dws.melt.matching_base.external.seals.MatcherSeals.match(MatcherSeals.java:265)
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherFile.match(MatcherFile.java:19)
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherURL.align(MatcherURL.java:52)
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherURL.align(MatcherURL.java:35)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionRunner.runMatcher(ExecutionRunner.java:56)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.Executor.run(Executor.java:167)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.Executor.run(Executor.java:88)
	at de.uni_mannheim.informatik.dws.melt.demomatcher.EvaluationExample2.main(EvaluationExample2.java:70)
2021-08-22 22:16:56 ERROR [main                          ] 59   in ExecutionRunner      - Exception during matching (matcher SEALS Matcher on testcase mouse-human-suite).
eu.sealsproject.platform.res.tool.api.ToolException: Tool exception
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherURL.align(MatcherURL.java:55)
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherURL.align(MatcherURL.java:35)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionRunner.runMatcher(ExecutionRunner.java:56)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.Executor.run(Executor.java:167)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.Executor.run(Executor.java:88)
	at de.uni_mannheim.informatik.dws.melt.demomatcher.EvaluationExample2.main(EvaluationExample2.java:70)
Caused by: de.uni_mannheim.informatik.dws.melt.matching_base.MatchingException: The result of seals matcher is an empty file.
	at de.uni_mannheim.informatik.dws.melt.matching_base.external.seals.MatcherSeals.match(MatcherSeals.java:265)
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherFile.match(MatcherFile.java:19)
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherURL.align(MatcherURL.java:52)
	... 5 more
2021-08-22 22:16:56 INFO  [main                          ] 64   in ExecutionRunner      - Running matcher SEALS Matcher on testcase mouse-human-suite (track anatomy_track) completed in 0 seconds.
2021-08-22 22:16:56 ERROR [main                          ] 67   in ExecutionRunner      - Matching task unsuccessful: output alignment equals null. (matcher: SEALS Matcher testcase: mouse-human-suite track: anatomy_track)
2021-08-22 22:16:56 INFO  [main                          ] 237  in EvaluatorCSV         - Writing alignment cube
The time is 1790 ms

**Comment by liweizhuo001** [comment] 2021-08-22 14:31
This is source code of  Evaluation

### public class EvaluationExample {

    public static void main(String[] args) {

        // STEP 1: Let's initialize the matchers we want to evaluate

    	 //SimpleStringMatcher classMatcher = new SimpleStringMatcher();
    	
    	// CASE 2: SEALS Package
        // If you have problems with your java version, have a look at our user guide on how to manually set
        // a path to JAVA 8 for SEALS: https://dwslab.github.io/melt/matcher-packaging/seals#evaluate-and-re-use-a-seals-package-with-melt
        
    	File sealsFile = loadFile("simpleSealsMatcher-1.0-seals_external.zip");
        MatcherSeals sealsMatcher = new MatcherSeals(sealsFile);

        // CASE 3: Web Docker Package
//        File dockerFile = loadFile("simplewebmatcher-1.0-web-latest.tar.gz");
//        MatcherDockerFile dockerMatcher = new MatcherDockerFile("simplewebmatcher-1.0-web", dockerFile);
        
        // STEP 2: Run (execute) the 3 matchers to obtain an ExecutionResultSet instance 

        // Let's add all tracks we want to evaluate to a list
        List<Track> tracks = new ArrayList<>();
        //tracks.add(TrackRepository.Conference.V1);
        //tracks.add(TrackRepository.Conference.V1_ALL_TESTCASES);
        tracks.add(TrackRepository.Anatomy.Default);

        // Let's add all matchers to a map (key: matcher name, value: matcher instance)
        Map<String, IOntologyMatchingToolBridge> matchers = new HashMap<>();
        //matchers.put("Class Matcher", classMatcher);
        matchers.put("SEALS Matcher", sealsMatcher);
        //matchers.put("simpleSealsMatcher-1.0-seals_external.zip", sealsMatcher);
    
        //matchers.put("Docker Matcher", dockerMatcher);
        
        // Let's run the matchers on the tracks:
        //ExecutionResultSet result = Executor.run(TrackRepository.Conference.V1.getTestCase("confof-sigkdd"), matchers);
       // ExecutionResultSet result = Executor.run(TrackRepository.Conference.V1_ALL_TESTCASES, matchers);
        ExecutionResultSet result = Executor.run(TrackRepository.Anatomy.Default, matchers);

        // Step 3: Use your favorite evaluator to interpret the result.
        //         The results are serialized in directory: "./results".
        EvaluatorCSV evaluatorCSV = new EvaluatorCSV(result);
        evaluatorCSV.writeToDirectory();
        
        long toc=System.currentTimeMillis();
        
        System.out.println("The time is "+(toc-tic)+" ms");
    }

    /**
     * Helper function to load files in class path that contain spaces.
     * @param fileName Name of the file.
     * @return File in case of success, else null.
     */
    private static File loadFile(String fileName){
        try {
            return FileUtils.toFile(EvaluationExample.class.getClassLoader().getResource(fileName).toURI().toURL());
        } catch (URISyntaxException | MalformedURLException exception){
            exception.printStackTrace();
            System.out.println("Could not load file.");
            return null;
        }
    }
}

We guess the key problem is **"simpleSealsMatcher-1.0-seals_external.zip"** is meaningless，which is packaged in **simpleSealsMatcher maven project** by **mvn clean package**.  Maybe we miss some key operations.
If this "zip" can not be evaluated in **EvaluationExample.java**,  we can not package our matcher as SEALS Package with MELT successfully.

**Comment by sven-h** [comment] 2021-08-22 14:48
Hi,

I packaged simpleSealsMatcher with `mvn clean package`as you described and evaluated with your script.
Unfortunately, I cannot reproduce the error.
Would it be possible that you share your packaged matcher (`simpleSealsMatcher-1.0-seals_external.zip`) ?
Maybe upload it via Google Driver, Dropbox or any other file sharing service and provide the link here.
If the file is small enough maybe you can also directly attach it in this issue.

Best regards
Sven

**Comment by liweizhuo001** [comment] 2021-08-22 15:58
[simpleSealsMatcher-1.0-seals_external.zip](https://github.com/dwslab/melt/files/7027671/simpleSealsMatcher-1.0-seals_external.zip)
The linke of Google Driver is https://drive.google.com/file/d/1bfnOBkr-xGFvCetwiEl-2jeZF2MSM4WD/view?usp=sharing

Thank you very much.

**Comment by sven-h** [comment] 2021-08-22 17:22
Thank you for your upload.
I tested the matcher on windows and again it worked fine.
I will try it out on linux as well to see if there are any OS specific errors.

**Comment by liweizhuo001** [comment] 2021-08-23 01:01
Thank you. I will try it.

**Do you show me the test file (EvaluationExample.java) or its maven project (evaluationExample project)? 

Again, **my key requirment is that https://github.com/dwslab/melt/tree/master/examples/simpleSealsMatcher needs to add an instantiated exampe (LevenshteinMatcher or SimpleStringMatcher extend by MatcherURL, MatcherYAAAJena or MatcherYAAAOwlApi).** 

There are four files called LevenshteinMatcher.java, LoadResourceMatcher.java, MatcherUrlExample.java, SimpleStringMatcher.java in src/main/java package and one file in src/test/java called EvaluateMatcher.java. The four files are class files, and latter is the test file. 

However, **I do not know which file will be run in the evalutation of EvaluationExample.java.** LevenshteinMatcher.java or SimpleStringMatcher.java or any others? So I do not how to exent my Matcher [GMap](https://github.com/liweizhuo001/GMap1.1) by this project or the corresponding file, which has finished three tracks in [OAEI 2015](https://github.com/liweizhuo001/GMap_oaei2015). 

There are any configure files? Because **"matchers.put("SEALS Matcher", sealsMatcher);"** or other sentences (shown below) do not provide any information to us. **Which matcher will be evluated in this EvaluationExample.java file. LevenshteinMatcher.java, LoadResourceMatcher.java, MatcherUrlExample.java, or SimpleStringMatcher.java, I do not know.**

```
### CASE 2: SEALS Package
// If you have problems with your java version, have a look at our user guide on how to manually set
// a path to JAVA 8 for SEALS: https://dwslab.github.io/melt/matcher-packaging/seals#evaluate-and-re-use-a-seals-package-with-melt
File sealsFile = loadFile("simpleSealsMatcher-1.0-seals_external.zip");**
MatcherSeals sealsMatcher = new MatcherSeals(sealsFile);

// Let's add all tracks we want to evaluate to a list
List<Track> tracks = new ArrayList<>();
tracks.add(TrackRepository.Anatomy.Default);

// Let's add all matchers to a map (key: matcher name, value: matcher instance)
Map<String, IOntologyMatchingToolBridge> matchers = new HashMap<>();
matchers.put("SEALS Matcher", sealsMatcher);

// Let's run the matchers on the tracks:
ExecutionResultSet result = Executor.run(TrackRepository.Anatomy.Default, matchers);

// Step 3: Use your favorite evaluator to interpret the result.
//         The results are serialized in directory: "./results".
EvaluatorCSV evaluatorCSV = new EvaluatorCSV(result);
evaluatorCSV.writeToDirectory();
```

Sincerely,  a new platform for international campaign without one detailed introduction (e.g., readme file for every operations in this propject) and an instantiated exampe (one concrete matcher such as SimpleStringMatcher to acheive all the progress that can successfully pass all the tests in any operation systems such as windows, linux, macOS) is very painful for our participators, specailly for old participators.

**Comment by sven-h** [comment] 2021-08-23 11:49
Hi,

it looks like you do not use java 8 which is a strict requirement for SEALS client which is executed in the background.
You do not need to execute the whole evaluation with java 8 but you can easily set the java8 command with:
```
File sealsFile = loadFile("simpleSealsMatcher-1.0-seals_external.zip");**
MatcherSeals sealsMatcher = new MatcherSeals(sealsFile);
sealsMatcher.setJavaCommand("...");
```
We also added a check that MatcherSeals really uses java8.

Best regards
Sven

**Comment by liweizhuo001** [comment] 2021-08-23 12:14
```
public static void main(String[] args) {
        File sealsZip = new File("<SEALS ZIP FILE PATH>");
        String java8command = "<PATH TO JAVA 8 EXECUTABLE>";

        // let's instantiate our seals matcher wrapper:
        MatcherSeals matcherSeals = new MatcherSeals(sealsZip);

        // if you do not have Java 8 as system java:
        matcherSeals.setJavaCommand(java8command);

        // let's run the matcher:
        ExecutionResultSet ers = Executor.run(TrackRepository.Anatomy.Default.getFirstTestCase(), matcherSeals);

        // finally, let's evaluate the execution result
        EvaluatorCSV evaluatorCSV = new EvaluatorCSV(ers);
        evaluatorCSV.writeToDirectory();
    }
```

Thank you, what does **java8command** or  **"<PATH TO JAVA 8 EXECUTABLE>"** look like? This is my mentioned about the importance of  **instantiated exampe**. My java version is "1.8.0_181". Do I need to Instanll Java 8?

**Comment by janothan** [comment] 2021-08-23 12:52
If you open your terminal and type `java -version` what is the output?

`java8command` simply is your Java 8 executable, more specifically the full path (particularly, if you have multiple Java versions installed). This is why we cannot set this for you since the path is specific to your machine.

For example, on my machine, I have Java 16 installed. Hence, I need to provide the Java 8 path. I do this by:
```
String java8command = "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java";
```

**Comment by liweizhuo001** [comment] 2021-08-23 13:44
The output of `java -verson` is 

```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```
Do you install Java 16 and Java 8 at the same time in your machine? If I have only one old java version. Do I need to Instanll Java 8?

**Comment by liweizhuo001** [comment] 2021-08-23 13:56
I instead this sentence `String java8command = "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java"; `of `"String java8command ="/Users/liweizhuo/Library/Java/JavaVirtualMachines/openjdk-14.0.2-1/Contents/Home/bin/java";`, 

```
public class SealsMatcherPlayground {
    public static void main(String[] args) throws ToolBridgeException, IOException {
        
    	//File sealsZip = new File("resources/simpleSealsMatcher-1.0-seals_external.zip");
    	File sealsZip = new File("simpleSealsMatcher-1.0-seals_external.zip");
        
        String java8command = "/Users/liweizhuo/Library/Java/JavaVirtualMachines/openjdk-14.0.2-1/Contents/Home/bin/java";

        // let's instantiate our seals matcher wrapper:
        MatcherSeals matcherSeals = new MatcherSeals(sealsZip);
             
        // if you do not have Java 8 as system java:
        matcherSeals.setJavaCommand(java8command);

        // let's run the matcher:
        ExecutionResultSet ers = Executor.run(TrackRepository.Anatomy.Default.getFirstTestCase(), matcherSeals);

        // finally, let's evaluate the execution result
        EvaluatorCSV evaluatorCSV = new EvaluatorCSV(ers);
        evaluatorCSV.writeToDirectory();
     
    }
}
```

However, the same error is reproduced shown below.
```
2021-08-23 21:52:38 INFO  [main                          ] 194  in MatcherSeals         - Unzip seals matcher simpleSealsMatcher-1.0-seals_external.zip now.
2021-08-23 21:52:38 INFO  [main                          ] 125  in Track                - Track cache folder is: /Users/liweizhuo/oaei_track_cache
2021-08-23 21:52:38 INFO  [main                          ] 48   in ExecutionRunner      - Running matcher MatcherSeals on testcase mouse-human-suite (track anatomy_track).
2021-08-23 21:52:38 INFO  [main                          ] 142  in ExternalProcess      - Execute now following external process (command, directory, custom environment variables):
2021-08-23 21:52:38 INFO  [main                          ] 143  in ExternalProcess      - command        : /Users/liweizhuo/Library/Java/JavaVirtualMachines/openjdk-14.0.2-1/Contents/Home/bin/java -jar /var/folders/9c/_pvrhxjs2c110syrwl6vy0b00000gn/T/seals-omt-client-v7.0.5.jar /var/folders/9c/_pvrhxjs2c110syrwl6vy0b00000gn/T/meltUnzip-3777365376522072318 -o file:/Users/liweizhuo/oaei_track_cache/oaei.webdatacommons.org/anatomy_track/anatomy_track-default/mouse-human-suite/source.rdf file:/Users/liweizhuo/oaei_track_cache/oaei.webdatacommons.org/anatomy_track/anatomy_track-default/mouse-human-suite/target.rdf -f /var/folders/9c/_pvrhxjs2c110syrwl6vy0b00000gn/T/alignment9187516815962242157.rdf -z
2021-08-23 21:52:38 INFO  [main                          ] 145  in ExternalProcess      - directory      : /private/var/folders/9c/_pvrhxjs2c110syrwl6vy0b00000gn/T/meltSealsHome-5659730593786793561
2021-08-23 21:52:38 INFO  [main                          ] 146  in ExternalProcess      - environmentVars: {SEALS_HOME=/private/var/folders/9c/_pvrhxjs2c110syrwl6vy0b00000gn/T/meltSealsHome-5659730593786793561}
2021-08-23 21:52:38 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): Exception in thread "main" java.lang.NoClassDefFoundError: eu/sealsproject/platform/res/tool/bundle/factory/PackageCreationException
2021-08-23 21:52:38 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): 	at java.base/java.lang.Class.forName0(Native Method)
2021-08-23 21:52:38 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): 	at java.base/java.lang.Class.forName(Class.java:427)
2021-08-23 21:52:38 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): 	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
2021-08-23 21:52:38 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): Caused by: java.lang.ClassNotFoundException: eu.sealsproject.platform.res.tool.bundle.factory.PackageCreationException
2021-08-23 21:52:38 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
2021-08-23 21:52:38 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
2021-08-23 21:52:38 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
2021-08-23 21:52:38 INFO  [ProcessStdErr                 ] 241  in MatcherSeals         - ExternalSEALS(Err): 	... 3 more
2021-08-23 21:52:38 ERROR [main                          ] 261  in MatcherSeals         - The result of seals matcher is an empty file. This typically happens when the matcher throws an error (see log messages of ExternalSEALS).In some cases this happens because the matcher does not expect an input alignment. You can solve this by setting  doNotUseInputAlignment to true in MatcherSeals.
2021-08-23 21:52:38 ERROR [main                          ] 54   in MatcherURL           - Tool Exception!
de.uni_mannheim.informatik.dws.melt.matching_base.MatchingException: The result of seals matcher is an empty file.
	at de.uni_mannheim.informatik.dws.melt.matching_base.external.seals.MatcherSeals.match(MatcherSeals.java:265)
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherFile.match(MatcherFile.java:19)
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherURL.align(MatcherURL.java:52)
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherURL.align(MatcherURL.java:35)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionRunner.runMatcher(ExecutionRunner.java:56)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.Executor.run(Executor.java:275)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.Executor.run(Executor.java:254)
	at de.uni_mannheim.informatik.dws.melt.demomatcher.SealsMatcherPlayground.main(SealsMatcherPlayground.java:31)
2021-08-23 21:52:38 ERROR [main                          ] 59   in ExecutionRunner      - Exception during matching (matcher MatcherSeals on testcase mouse-human-suite).
eu.sealsproject.platform.res.tool.api.ToolException: Tool exception
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherURL.align(MatcherURL.java:55)
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherURL.align(MatcherURL.java:35)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionRunner.runMatcher(ExecutionRunner.java:56)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.Executor.run(Executor.java:275)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.Executor.run(Executor.java:254)
	at de.uni_mannheim.informatik.dws.melt.demomatcher.SealsMatcherPlayground.main(SealsMatcherPlayground.java:31)
Caused by: de.uni_mannheim.informatik.dws.melt.matching_base.MatchingException: The result of seals matcher is an empty file.
	at de.uni_mannheim.informatik.dws.melt.matching_base.external.seals.MatcherSeals.match(MatcherSeals.java:265)
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherFile.match(MatcherFile.java:19)
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherURL.align(MatcherURL.java:52)
	... 5 more
2021-08-23 21:52:38 INFO  [main                          ] 64   in ExecutionRunner      - Running matcher MatcherSeals on testcase mouse-human-suite (track anatomy_track) completed in 0 seconds.
2021-08-23 21:52:38 ERROR [main                          ] 67   in ExecutionRunner      - Matching task unsuccessful: output alignment equals null. (matcher: MatcherSeals testcase: mouse-human-suite track: anatomy_track)
2021-08-23 21:52:39 INFO  [main                          ] 237  in EvaluatorCSV         - Writing alignment cube

```

**Comment by liweizhuo001** [comment] 2021-08-23 15:08
However, instantiating one example (e.g., SimpleStringMatcher extend by MatcherYAAAOwlApi) is still one challenge for us because some of methods parsing ontologies can not be reused such as  c.getDisjointClasses(onto);  op.getDomains(onto);  op.getRanges(onto), where c is OWLClass, op is OWLObjectProperty.

Add the new dependency in pom.xml file **can not solve this probelm!!!**

```
<dependency>
            <groupId>net.sourceforge.owlapi</groupId>
            <artifactId>owlapi-distribution</artifactId>
            <version>5.1.9</version>
</dependency>
```

The related issue is still processing in [issues/102](https://github.com/dwslab/melt/issues/102)

**Comment by alisea47** [comment] 2021-08-23 16:10
hi, I meet the similar problem, I download this zip from the link liweizhuo001 provide. When I try to run the code, the error message is:
```
de.uni_mannheim.informatik.dws.melt.matching_base.MatchingException: The result of seals matcher is an empty file.
	at de.uni_mannheim.informatik.dws.melt.matching_base.external.seals.MatcherSeals.match(MatcherSeals.java:265)
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherFile.match(MatcherFile.java:19)
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherURL.align(MatcherURL.java:52)
	at de.uni_mannheim.informatik.dws.melt.matching_base.MatcherURL.align(MatcherURL.java:35)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.ExecutionRunner.runMatcher(ExecutionRunner.java:56)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.Executor.run(Executor.java:167)
	at de.uni_mannheim.informatik.dws.melt.matching_eval.Executor.run(Executor.java:88)
	at de.uni_mannheim.informatik.dws.melt.demomatcher.EvaluationExample.main(EvaluationExample.java:67)
```
I use windows 10, and my java version:
```
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)
```

I think i need't add ` String java8command = "<PATH TO JAVA 8 EXECUTABLE>";`. But even I add this sentence, the error above still appeared.

> [simpleSealsMatcher-1.0-seals_external.zip](https://github.com/dwslab/melt/files/7027671/simpleSealsMatcher-1.0-seals_external.zip)
> The link of Google Driver is https://drive.google.com/file/d/1bfnOBkr-xGFvCetwiEl-2jeZF2MSM4WD/view?usp=sharing
> 
> Thank you very much.

**Comment by alisea47** [comment] 2021-08-23 16:31
And here is my project https://drive.google.com/file/d/1RHLQ7_KVjcp-tzfqn46t3rz2CIFMQFrk/view?usp=sharing
Could you please have a look what the problem is?
Thank u very much!

**Comment by sven-h** [comment] 2021-08-24 11:48
Hi @alisea47,

the link you provided is protected. I already requested to download the content.
Maybe we can discuss your issue in further in #101 .
It would be also helpful if you upload the full log file there.

Best regards
Sven

**Comment by sven-h** [comment] 2021-08-24 11:49
Hi @liweizhuo001 ,

if this issue is solved for you, please close it or otherwise let me know what is missing.

Best regards
Sven

**Closed** 2021-08-24 13:06 UTC
